# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_outlet.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'control_outlet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ontrol_outlet.proto\x12\x12Syncing_Battleship\"#\n\x11SessionLaunchInfo\x12\x0e\n\x06hostId\x18\x01 \x01(\t\"=\n\x0eNewSessionInfo\x12\x11\n\tsessionId\x18\x01 \x01(\x05\x12\x18\n\x10sourceOfTruthKey\x18\x02 \x01(\t\"5\n\x0eWelcomeRequest\x12\x11\n\tsessionId\x18\x01 \x01(\x05\x12\x10\n\x08playerId\x18\x02 \x01(\t\"\"\n\x0fWelcomeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xbc\x01\n\x11SyncControlOutlet\x12S\n\x06Launch\x12%.Syncing_Battleship.SessionLaunchInfo\x1a\".Syncing_Battleship.NewSessionInfo\x12R\n\x07Welcome\x12\".Syncing_Battleship.WelcomeRequest\x1a#.Syncing_Battleship.WelcomeResponseB!\xaa\x02\x1eSyncing_Battleship_gRPC_Outletb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_outlet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\036Syncing_Battleship_gRPC_Outlet'
  _globals['_SESSIONLAUNCHINFO']._serialized_start=44
  _globals['_SESSIONLAUNCHINFO']._serialized_end=79
  _globals['_NEWSESSIONINFO']._serialized_start=81
  _globals['_NEWSESSIONINFO']._serialized_end=142
  _globals['_WELCOMEREQUEST']._serialized_start=144
  _globals['_WELCOMEREQUEST']._serialized_end=197
  _globals['_WELCOMERESPONSE']._serialized_start=199
  _globals['_WELCOMERESPONSE']._serialized_end=233
  _globals['_SYNCCONTROLOUTLET']._serialized_start=236
  _globals['_SYNCCONTROLOUTLET']._serialized_end=424
# @@protoc_insertion_point(module_scope)
